export interface DailyChapter {
  id: string;
  title: string;
  character: string;
  source: string;
  category: "Mythology" | "Hindu Mythology" | "Literature" | "Film" | "Anime" | "Games" | "History" | "Philosophy";
  theme: string;
  quote: string;
  story: string;
  lesson: string;
  readMore?: string;
}

export const dailyChapters: DailyChapter[] = [
  {
    id: "achilles-rage",
    title: "The Rage That Wasn't About War",
    character: "Achilles",
    source: "The Iliad · Greek Mythology",
    category: "Mythology",
    theme: "Purpose",
    quote: "I will not fight for Agamemnon's glory.",
    story: "Achilles was the greatest warrior alive — yet he withdrew from battle not from cowardice, but from rage at fighting someone else's war. His anger wasn't weakness. It was the refusal to let another man define his worth. The Greeks nearly lost everything without him. When he returned, it wasn't for glory — it was for Patroclus, for meaning, for a fight that was finally his.",
    lesson: "Sometimes the bravest thing is refusing to fight until the battle is yours.",
    readMore: "The Iliad by Homer",
  },
  {
    id: "frodo-return",
    title: "The Hero Who Couldn't Go Home",
    character: "Frodo Baggins",
    source: "The Lord of the Rings",
    category: "Literature",
    theme: "Change",
    quote: "How do you pick up the threads of an old life? How do you go on, when in your heart you begin to understand there is no going back?",
    story: "Frodo saved Middle-earth. He destroyed the Ring. He came home to the Shire — green, peaceful, unchanged. But he was not unchanged. The wound never healed. The quiet hills felt too small for what he had carried. He didn't fail by leaving. He succeeded by surviving what no hobbit was meant to survive.",
    lesson: "You don't owe your old self a resurrection. Some journeys change you beyond return.",
    readMore: "The Lord of the Rings by J.R.R. Tolkien",
  },
  {
    id: "guts-keep-moving",
    title: "The Man Who Refused to Break",
    character: "Guts",
    source: "Berserk",
    category: "Anime",
    theme: "Perseverance",
    quote: "If you're always worried about crushing the ants beneath you, you won't be able to walk.",
    story: "Guts lost everything — friends, love, limb, innocence. The world broke him again and again. He never became gentle. He never became cruel either. He kept moving forward with a sword too large for any normal man, not because he believed in happy endings, but because stopping meant death — and he chose life, even when life was pain.",
    lesson: "Bravery isn't believing it gets easier. It's walking anyway.",
    readMore: "Berserk by Kentaro Miura",
  },
  {
    id: "kratos-better",
    title: "The Ghost Who Became a Father",
    character: "Kratos",
    source: "God of War",
    category: "Games",
    theme: "Redemption",
    quote: "Do not be sorry. Be better.",
    story: "Kratos was the Ghost of Sparta — a god-killer drenched in blood. He mourned the monster he was and feared the monster he could become again. But when Atreus looked at him, he didn't try to resurrect the old Kratos. He tried to become someone the old Kratos could never have been. Redemption wasn't erasing the past. It was outgrowing it.",
    lesson: "Don't be sorry for who you were. Become someone your past self couldn't imagine.",
    readMore: "God of War (2018)",
  },
  {
    id: "mandela-fear",
    title: "Twenty-Seven Years in a Cell",
    character: "Nelson Mandela",
    source: "Long Walk to Freedom",
    category: "History",
    theme: "Courage",
    quote: "I learned that courage was not the absence of fear, but the triumph over it.",
    story: "Mandela spent 27 years in prison for fighting apartheid. When he emerged, he could have led a nation into revenge. Instead he led it toward reconciliation — not because he wasn't angry, but because he understood that freedom without forgiveness would only birth new chains.",
    lesson: "The bravest people aren't fearless. They act despite the fear.",
    readMore: "Long Walk to Freedom",
  },
  {
    id: "camus-sisyphus",
    title: "The Man Who Pushed Forever",
    character: "Sisyphus",
    source: "Greek Mythology · Camus",
    category: "Philosophy",
    theme: "Meaning",
    quote: "One must imagine Sisyphus happy.",
    story: "The gods condemned Sisyphus to push a boulder uphill for eternity — only to watch it roll down every time he reached the top. Absurd. Futile. Yet Camus said we must imagine him happy — not because the task matters, but because choosing to push anyway is an act of defiance against meaninglessness.",
    lesson: "When the work feels pointless, the rebellion is continuing anyway.",
    readMore: "The Myth of Sisyphus by Albert Camus",
  },
  {
    id: "arthur-redemption",
    title: "The Outlaw's Last Ride",
    character: "Arthur Morgan",
    source: "Red Dead Redemption 2",
    category: "Games",
    theme: "Mortality",
    quote: "We can't change what's done. We can only move on.",
    story: "Arthur Morgan was dying. The life he'd lived — robbing, killing, following a man who'd lost his way — couldn't be undone. But in his final days, he chose small acts of grace. He helped strangers. He saved John Marston's family. He became good not by erasing his sins, but by spending his last breaths on something that mattered.",
    lesson: "It's never too late to decide who you are in the time you have left.",
    readMore: "Red Dead Redemption 2",
  },
  {
    id: "luffy-freedom",
    title: "The Boy Who Wanted Freedom",
    character: "Monkey D. Luffy",
    source: "One Piece",
    category: "Anime",
    theme: "Freedom",
    quote: "I don't want to conquer anything. I just think the guy with the most freedom in this ocean is the Pirate King!",
    story: "While others sought treasure and power, Luffy sought freedom — for himself and everyone he loved. He lost allies, faced impossible enemies, and never stopped laughing. Not because the world was kind, but because joy was his rebellion against a world that wanted him broken.",
    lesson: "The greatest adventure isn't conquering — it's refusing to be caged.",
    readMore: "One Piece by Eiichiro Oda",
  },
  {
    id: "shawshank-hope",
    title: "Hope in a Place Built to Kill It",
    character: "Andy Dufresne",
    source: "The Shawshank Redemption",
    category: "Film",
    theme: "Hope",
    quote: "Remember, Red. Hope is a good thing, maybe the best of things, and no good thing ever dies.",
    story: "Andy was innocent, sentenced to life in Shawshank. For twenty years he tunneled through rock with a tiny hammer — one chip at a time — while playing Mozart for prisoners who'd forgotten beauty existed. He didn't escape through violence. He escaped through patience, intelligence, and an unkillable belief that the outside still existed.",
    lesson: "Hope isn't naive. Sometimes it's the only tool sharp enough to cut through stone.",
    readMore: "The Shawshank Redemption",
  },
  {
    id: "odysseus-journey",
    title: "Ten Years to Get Home",
    character: "Odysseus",
    source: "The Odyssey · Greek Mythology",
    category: "Mythology",
    theme: "Perseverance",
    quote: "There is a time for many words, and there is also a time for sleep.",
    story: "Odysseus fought ten years at Troy, then spent ten more trying to get home — past sirens, cyclops, witches, and the wrath of gods. His crew died. His youth faded. When he finally reached Ithaca, his wife didn't recognize him at first. The journey had cost him everything except the will to finish.",
    lesson: "Home isn't a place you reach quickly. It's what you keep walking toward.",
    readMore: "The Odyssey by Homer",
  },
  {
    id: "dumbledore-light",
    title: "Happiness in the Dark",
    character: "Albus Dumbledore",
    source: "Harry Potter",
    category: "Literature",
    theme: "Light",
    quote: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    story: "Dumbledore carried guilt his entire life — for his sister, for Grindelwald, for the boy he knew he was raising to die. He smiled anyway. Not because the darkness wasn't real, but because he chose to be the light others needed, even when he felt none himself.",
    lesson: "You can be broken and still be someone's reason to believe in good.",
    readMore: "Harry Potter and the Prisoner of Azkaban",
  },
  {
    id: "musashi-way",
    title: "The Sword Saint's Solitude",
    character: "Miyamoto Musashi",
    source: "History · Vagabond",
    category: "History",
    theme: "Discipline",
    quote: "Do nothing that is of no use.",
    story: "Musashi won over sixty duels. He never lost. Yet his greatest battles were internal — against ego, against distraction, against the comfort of being known as invincible. He spent his final years in a cave, writing about the way of strategy, having learned that mastery without wisdom is just violence with skill.",
    lesson: "Strength without purpose is noise. Discipline is choosing what matters.",
    readMore: "The Book of Five Rings",
  },
  {
    id: "bojack-change",
    title: "It Gets Easier",
    character: "BoJack Horseman",
    source: "BoJack Horseman",
    category: "Film",
    theme: "Change",
    quote: "It gets easier. Every day it gets a little easier. But you gotta do it every day — that's the hard part.",
    story: "BoJack had fame, money, and self-loathing in equal measure. He hurt everyone who loved him and hated himself for it. The show never promised he'd be fixed. It promised that change is possible — but only if you show up every single day and choose not to be the person you were yesterday.",
    lesson: "Healing isn't an event. It's a daily decision you keep making.",
    readMore: "BoJack Horseman",
  },
  {
    id: "atticus-stand",
    title: "Standing When No One Else Will",
    character: "Atticus Finch",
    source: "To Kill a Mockingbird",
    category: "Literature",
    theme: "Integrity",
    quote: "The one thing that doesn't abide by majority rule is a person's conscience.",
    story: "Atticus knew he would lose the trial. He defended Tom Robinson anyway — in a town that hated him for it, at the cost of his family's safety. He didn't fight because he expected victory. He fought because some things are wrong even when everyone agrees they're right.",
    lesson: "Courage is doing right when the crowd has already chosen wrong.",
    readMore: "To Kill a Mockingbird by Harper Lee",
  },
  {
    id: "artorias-dark",
    title: "The Knight Who Fought the Abyss",
    character: "Artorias the Abysswalker",
    source: "Dark Souls",
    category: "Games",
    theme: "Sacrifice",
    quote: "If thou art human, then surely thou art familiar with death and loss.",
    story: "Artorias was Gwyn's greatest knight. When the Abyss threatened to consume everything, he went alone into darkness to stop it. He failed — corrupted, broken, remembered only as a legend of tragedy. But his sacrifice bought the world time. Not every hero gets to win. Some just hold the line long enough for others to continue.",
    lesson: "Some battles are worth fighting even when you know you won't walk away.",
    readMore: "Dark Souls · Artorias of the Abyss",
  },
  {
    id: "siddhartha-search",
    title: "The Search for Yourself",
    character: "Siddhartha",
    source: "Siddhartha · Hermann Hesse",
    category: "Literature",
    theme: "Identity",
    quote: "I can think. I can wait. I can fast.",
    story: "Siddhartha was a Brahmin's son, a ascetic, a merchant, a lover, a ferryman. He tried every path to wisdom and found each incomplete. Enlightenment didn't come from teachers or books. It came when he stopped searching outside and listened to the river — to the unity of all experience, including pain.",
    lesson: "You are not one version of yourself. You are every version you've survived.",
    readMore: "Siddhartha by Hermann Hesse",
  },
  {
    id: "eren-freedom",
    title: "Freedom at Any Cost",
    character: "Eren Yeager",
    source: "Attack on Titan",
    category: "Anime",
    theme: "Freedom",
    quote: "If you win, you live. If you lose, you die. If you don't fight, you can't win.",
    story: "Eren started as a boy who wanted to see the ocean. He became something terrifying to achieve freedom — for himself, for his people, at a cost that shattered the world. His story asks the hardest question: what would you destroy to be free? And would you recognize yourself afterward?",
    lesson: "Freedom isn't free. The question is what you're willing to become to claim it.",
    readMore: "Attack on Titan by Hajime Isayama",
  },
  {
    id: "van-gogh-star",
    title: "Painting Stars While Breaking",
    character: "Vincent van Gogh",
    source: "History",
    category: "History",
    theme: "Creation",
    quote: "I am seeking, I am striving, I am in it with all my heart.",
    story: "Van Gogh sold one painting in his lifetime. He battled mental illness, poverty, and isolation. He painted over 2,000 works anyway — sunflowers, starry nights, wheat fields on fire with color. He didn't create because he was happy. He created because making beauty was the only way he knew to stay alive.",
    lesson: "Your work doesn't need an audience to matter. Making it is the act of courage.",
    readMore: "Letters to Theo · Van Gogh",
  },
  {
    id: "paul-atreides",
    title: "The Boy Who Became a God",
    character: "Paul Atreides",
    source: "Dune",
    category: "Literature",
    theme: "Power",
    quote: "I must not fear. Fear is the mind-killer.",
    story: "Paul didn't want to be a messiah. The path was laid before him by centuries of manipulation — the Bene Gesserit, the spice, the visions of a holy war he couldn't stop. He seized power to protect his family and unleashed something that consumed the galaxy. Every gift came with a shadow.",
    lesson: "Be careful what you're destined for. Destiny can be a cage dressed as purpose.",
    readMore: "Dune by Frank Herbert",
  },
  {
    id: "rocky-balance",
    title: "The Nobody Who Went the Distance",
    character: "Rocky Balboa",
    source: "Rocky",
    category: "Film",
    theme: "Grit",
    quote: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.",
    story: "Rocky was a debt collector who never made it. Apollo Creed gave him a shot nobody thought he deserved. He lost the fight — but he went fifteen rounds with the champion of the world. He didn't need to win. He needed to prove to himself that he wasn't a bum. That was enough.",
    lesson: "Winning isn't always the goal. Sometimes it's proving you won't stay down.",
    readMore: "Rocky (1976)",
  },
  {
    id: "aurelius-mind",
    title: "The Emperor's Private Journal",
    character: "Marcus Aurelius",
    source: "Meditations · Stoicism",
    category: "Philosophy",
    theme: "Control",
    quote: "You have power over your mind — not outside events. Realize this, and you will find strength.",
    story: "Marcus Aurelius ruled the Roman Empire at its height — and wrote his deepest thoughts in a journal never meant to be read. Plague, war, betrayal, the death of children. He didn't complain. He reminded himself: control what you can, accept what you can't, and act with virtue regardless.",
    lesson: "Peace isn't having no problems. It's knowing which battles are yours to fight.",
    readMore: "Meditations by Marcus Aurelius",
  },
  {
    id: "joel-ellie",
    title: "Saving One Person in the End of the World",
    character: "Joel Miller",
    source: "The Last of Us",
    category: "Games",
    theme: "Love",
    quote: "I struggled for a long time with survivin', and you—",
    story: "Joel lost his daughter on the first day of the apocalypse. Twenty years later, he found purpose in Ellie — not as a cure for humanity, but as a daughter he chose. When the world demanded her sacrifice, he chose her over everyone. Was it right? The story doesn't answer. It asks what you'd do for one person you love.",
    lesson: "Sometimes love isn't noble. It's choosing one person over the world.",
    readMore: "The Last of Us",
  },
  {
    id: "simba-return",
    title: "The King Who Ran Away",
    character: "Simba",
    source: "The Lion King",
    category: "Film",
    theme: "Responsibility",
    quote: "Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.",
    story: "Simba ran from Pride Rock believing he caused his father's death. He built a carefree life hiding from guilt. But the Pride Lands rotted without him. Rafiki didn't tell him to forget the past — he told him to return to it. Leadership wasn't about being fearless. It was about facing what he'd done and who he was meant to be.",
    lesson: "Running from your story doesn't end it. It just pauses it until you're ready.",
    readMore: "The Lion King",
  },
  {
    id: "gandalf-time",
    title: "All We Have to Decide",
    character: "Gandalf",
    source: "The Lord of the Rings",
    category: "Literature",
    theme: "Choice",
    quote: "All we have to decide is what to do with the time that is given us.",
    story: "Gandalf was thousands of years old — a Maia sent to Middle-earth to guide, not to rule. He fell fighting a demon and returned changed. He carried the weight of knowing Sauron could not be defeated by strength alone. His power was never magic. It was showing ordinary people they were capable of extraordinary things.",
    lesson: "You can't choose your moment. You can only choose what you do inside it.",
    readMore: "The Lord of the Rings",
  },
  {
    id: "levi-continue",
    title: "The Soldier Who Kept Choosing",
    character: "Levi Ackerman",
    source: "Attack on Titan",
    category: "Anime",
    theme: "Duty",
    quote: "The only thing we're allowed to do is believe that we won't regret the choice we made.",
    story: "Levi lost every squad he ever led. He cleaned their blood off his blades and kept fighting. Not because he believed in victory — but because someone had to make the impossible choices so others could live. His cruelty was compassion compressed into action.",
    lesson: "Strength sometimes looks like making the hard choice and carrying it alone.",
    readMore: "Attack on Titan",
  },
  {
    id: "arjuna-doubt",
    title: "The Warrior Who Froze on the Battlefield",
    character: "Arjuna",
    source: "Bhagavad Gita · Mahabharata",
    category: "Hindu Mythology",
    theme: "Duty",
    quote: "I will not fight. What pleasure can we have in killing our own kinsmen?",
    story: "On the eve of the greatest war in history, Arjuna — the finest archer alive — dropped his bow. He saw his teachers, uncles, and cousins across the battlefield. His hands trembled. His mind collapsed under the weight of duty versus love. Krishna did not tell him to stop feeling. He taught him that action without attachment to outcome is the path through impossible choices. Arjuna picked up the bow not because the war was easy, but because some duties break you before they make you.",
    lesson: "Courage isn't the absence of doubt. It's acting when every part of you wants to walk away.",
    readMore: "Bhagavad Gita",
  },
  {
    id: "karna-loyalty",
    title: "The Sun God's Son Nobody Knew",
    character: "Karna",
    source: "Mahabharata",
    category: "Hindu Mythology",
    theme: "Honor",
    quote: "Even if the whole world abandons you, your word must not abandon you.",
    story: "Karna was born a prince but raised a charioteer's son. The world mocked his origin while he surpassed every warrior on the field. When he learned his true identity — that he had been fighting his own brothers — he chose loyalty to the friend who stood by him when no one else would. He gave away his divine armor knowing it would cost him his life. He was wronged by fate at every turn. He never wronged his own conscience.",
    lesson: "You cannot control how the world treats you. You can control whether you betray yourself.",
    readMore: "Mahabharata",
  },
  {
    id: "rama-exile",
    title: "Fourteen Years in the Forest",
    character: "Rama",
    source: "Ramayana",
    category: "Hindu Mythology",
    theme: "Dharma",
    quote: "The path of righteousness is often the harder path. Walk it anyway.",
    story: "Rama was heir to the throne of Ayodhya — beloved, righteous, about to be crowned. On the eve of his coronation, he was exiled to the forest for fourteen years on his father's word. He did not rage. He did not seize the kingdom by force. He walked into exile because a promise had been made, and dharma mattered more than a crown. His suffering was not weakness — it was the price of being a man who could not bend his integrity.",
    lesson: "Doing the right thing when it costs you everything — that is the measure of character.",
    readMore: "Ramayana by Valmiki",
  },
  {
    id: "sita-fire",
    title: "The Fire That Could Not Burn Her",
    character: "Sita",
    source: "Ramayana",
    category: "Hindu Mythology",
    theme: "Resilience",
    quote: "My purity is not something others can take from me. It is mine alone.",
    story: "Sita was abducted and imprisoned in Lanka — tested, threatened, surrounded by demons. She refused every offer of comfort that came with surrender. When Rama rescued her, the world doubted her anyway. She walked through fire to prove what needed no proof. The flames did not touch her. Her strength was never in the rescue. It was in surviving with her soul intact when everything was taken from her.",
    lesson: "What they do to you is not who you are. Your dignity survives their cruelty.",
    readMore: "Ramayana by Valmiki",
  },
  {
    id: "hanuman-leap",
    title: "The Leap Across the Ocean",
    character: "Hanuman",
    source: "Ramayana",
    category: "Hindu Mythology",
    theme: "Devotion",
    quote: "When you serve something greater than yourself, impossible distances shrink.",
    story: "Hanuman was told the ocean was too vast to cross. He had forgotten his own power — cursed to not know his strength until reminded by love and duty. When Jambavan told him what he truly was, Hanuman grew to the size of a mountain and leapt across the sea to find Sita. Not for glory. Not for reward. Because Rama needed him, and devotion makes cowards into forces of nature.",
    lesson: "You have more power than you know. It awakens when something matters more than fear.",
    readMore: "Ramayana by Valmiki",
  },
  {
    id: "yudhishthira-truth",
    title: "The King Who Never Lied",
    character: "Yudhishthira",
    source: "Mahabharata",
    category: "Hindu Mythology",
    theme: "Truth",
    quote: "Truth alone triumphs. Not quickly. Not easily. But always.",
    story: "Yudhishthira lost everything — his kingdom, his brothers, his wife — in a game of dice rigged against him. He endured thirteen years of exile in forests and disguise. When offered a chance to end the war with a single lie, he refused. When the great war ended and he stood at heaven's gate, he would not enter without the dog that followed him — who was Dharma itself in disguise. He chose truth when lies would have been easier at every turn.",
    lesson: "Integrity is not what you proclaim. It's what you refuse to trade away.",
    readMore: "Mahabharata",
  },
  {
    id: "bhishma-vow",
    title: "The Terrible Vow",
    character: "Bhishma",
    source: "Mahabharata",
    category: "Hindu Mythology",
    theme: "Sacrifice",
    quote: "A vow spoken in truth binds not just the tongue — it binds the soul.",
    story: "Devavrata was a prince who gave up the throne, marriage, and children so his father could marry the woman he loved. The gods themselves named him Bhishma — the terrible one — for the weight of that vow. He kept it for a lifetime, fighting on the wrong side of the war because his vow bound him to the throne, not to justice. His tragedy teaches that even noble sacrifices can become prisons if you never allow yourself to change.",
    lesson: "Keep your word — but know which promises are worth the life they cost.",
    readMore: "Mahabharata",
  },
  {
    id: "ekalavya-mastery",
    title: "The Thumb He Gave Away",
    character: "Ekalavya",
    source: "Mahabharata",
    category: "Hindu Mythology",
    theme: "Mastery",
    quote: "Guru dakshina is not a fee. It is the price of becoming.",
    story: "Ekalavya was a tribal boy rejected by the great guru Dronacharya. He built a statue of his teacher and practiced alone in the forest until he surpassed Arjuna himself. When Drona saw this, he demanded guru dakshina — payment for teaching. Ekalavya had learned from a statue, not the man. Still, he cut off his own right thumb without hesitation. The greatest archer destroyed his gift to honor a debt. The world called it injustice. He called it dharma.",
    lesson: "Mastery demands sacrifice. The question is whether the price serves your soul or breaks it.",
    readMore: "Mahabharata",
  },
  {
    id: "savitri-death",
    title: "The Woman Who Argued with Death",
    character: "Savitri",
    source: "Mahabharata",
    category: "Hindu Mythology",
    theme: "Love",
    quote: "Where there is true love and true penance, death itself can be moved.",
    story: "Savitri chose her own husband — Satyavan — knowing the sage Narada had foretold he would die in one year. When Yama came for his soul, Savitri followed. She spoke with such wisdom, devotion, and clarity that the god of death himself was moved. He offered her boons. She chose her father-in-law's sight, her husband's kingdom, and finally — her husband's life. Love did not defeat death through force. It defeated death through unwavering presence.",
    lesson: "Some things are worth standing in front of death for. Love is one of them.",
    readMore: "Mahabharata · Savitri and Satyavan",
  },
  {
    id: "krishna-karma",
    title: "Act Without Clinging",
    character: "Krishna",
    source: "Bhagavad Gita",
    category: "Hindu Mythology",
    theme: "Detachment",
    quote: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action.",
    story: "Krishna spoke to Arjuna not as a god demanding worship, but as a friend explaining the nature of action. Do your duty. Fight if you must. But do not attach your soul to victory or defeat, praise or blame. The warrior who acts without clinging is free even on the battlefield. This was not indifference — it was the deepest form of engagement, performed without the ego that makes every loss unbearable.",
    lesson: "Give everything to the work. Release your grip on the outcome.",
    readMore: "Bhagavad Gita",
  },
  {
    id: "shiva-destruction",
    title: "The God Who Dances in the Fire",
    character: "Shiva",
    source: "Hindu Mythology · Puranas",
    category: "Hindu Mythology",
    theme: "Transformation",
    quote: "What Shiva destroys, he destroys so something truer can be born.",
    story: "Shiva is the destroyer — but destruction in Hindu thought is not evil. It is the necessary end of what has outlived its purpose. He dances the Tandava in cemeteries and cremation grounds, surrounded by ashes, because he understands what the living forget: every ending is the opening of a new cycle. When your old self dies — your job, your identity, your certainty — Shiva is not punishing you. He is making room.",
    lesson: "When everything falls apart, something in you is being cleared for what comes next.",
    readMore: "Shiva Purana",
  },
];

export function getChapterForToday(): DailyChapter {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return dailyChapters[dayOfYear % dailyChapters.length];
}

export function getRandomChapter(excludeId?: string): DailyChapter {
  const pool = excludeId
    ? dailyChapters.filter((c) => c.id !== excludeId)
    : dailyChapters;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getChapterById(id: string): DailyChapter | undefined {
  return dailyChapters.find((c) => c.id === id);
}
